theme = "tokyonight"

[editor]
text-width = 100
line-number = "relative"
insert-final-newline = false
bufferline = "always"
auto-format = false

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = true
