[language-server.jinja-lsp]
command = "jinja-lsp"
config = { template_extensions = ["njk"] }
timeout = 5

[language-server.graphql]
command = "graphql-lsp"
args = ["server", "-m", "stream"]

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
schemaStore = { enable = false }

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"./script/schema/aws-spec.schema.json" = "*/aws.yaml"
"./script/schema/component-spec.schema.json" = "*/component.yaml"
"./script/schema/dynamodb-action.schema.json" = "*/action/*/*.yaml"
"./script/schema/formats-spec.schema.json" = "*/formats.yaml"
"./script/schema/json-schema_draft-07.schema.json" = "*/*.schema.yaml"

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "jinja"
language-servers = ["jinja-lsp"]
file-types = [{ glob = "*.njk" }]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "codebook",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "csv"
auto-format = false

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "c"
language-servers = ["clangd", "codebook"]

